import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FriendshipsAreMadeHere from "@/components/FriendshipsAreMadeHere";
import { Poppins } from "next/font/google";
import Image from "next/image";
import bgImage from "../../assets/backgorund.svg";
import { AOSInit } from "@/components/AOSInit";

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'], variable: '--font-poppins' });

const neuSansTrial = localFont({
  src: [
    {
      path: "./fonts/neusanstrial-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/neusanstrial-regularitalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/neusanstrial-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/neusanstrial-mediumitalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/neusanstrial-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/neusanstrial-bolditalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/neusanstrial-black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/neusanstrial-blackitalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-neusanstrial",
});

export const metadata = {
  title: "BlackLinx",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${neuSansTrial.variable} ${poppins.variable} antialiased relative min-h-screen`}>
        <AOSInit />
        {/* Global Background Image */}
        <div className="fixed inset-0 pointer-events-none z-[-1]">
          <Image
            src={bgImage}
            alt="Global background texture"
            fill
            style={{ objectFit: "cover" }}
            quality={100}
            priority
          />
        </div>

        <Header />
        <main>{children}</main>
        <FriendshipsAreMadeHere />
        <Footer />
      </body>
    </html>
  );
}
